### ISSUE TITLE
The provided SBML model is not valid

### ISSUE THREAD

**Issue by Xuerlock** [qLSLab/integrate#4]
I'm trying to test the pipeline with provided model **ENGRO2.xml**, but the getGPRsFromModel.py said that it was not a valid SBML model (The wrong information is attached below). I have validated the model on https://synonym.caltech.edu/validator_servlet/ and the report shows that it passed the validation and is a SBML model (although with some warnings). Is there any problem with the model file?

[integrate]$ python pipeline/getGPRsFromModel.py
Set parameter Username
Traceback (most recent call last):
  File "anaconda/lib/python3.8/site-packages/cobra/io/sbml.py", line 244, in read_sbml_model
    return _sbml_to_model(doc, number=number, f_replace=f_replace, **kwargs)
  File "anaconda/lib/python3.8/site-packages/cobra/io/sbml.py", line 366, in _sbml_to_model
    cobra_model = Model(model_id)
  File "anaconda/lib/python3.8/site-packages/cobra/core/model.py", line 113, in __init__
    self._solver = interface.Model()
  File "anaconda/lib/python3.8/site-packages/optlang/interface.py", line 1191, in __init__
    self._initialize_problem()
  File "anaconda/lib/python3.8/site-packages/optlang/gurobi_interface.py", line 531, in _initialize_problem
    self.problem = gurobipy.Model()
  File "src/gurobipy/model.pxi", line 68, in gurobipy.Model.__init__
  File "src/gurobipy/gurobi.pxi", line 32, in gurobipy.gurobi._getdefaultenv
  File "src/gurobipy/env.pxi", line 62, in gurobipy.Env.__init__
gurobipy.GurobiError: HostID mismatch (licensed to 38f6002f, hostid is 38f6002a)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pipeline/getGPRsFromModel.py", line 23, in <module>
    model = cb.io.read_sbml_model(os.path.join(MODELDIR, modelId + '.xml'))
  File "anaconda/lib/python3.8/site-packages/cobra/io/sbml.py", line 258, in read_sbml_model
    raise cobra_error from original_error
cobra.io.sbml.CobraSBMLError: Something went wrong reading the SBML model. Most likely the SBML model is not valid. Please check that your model is valid using the `cobra.io.sbml.validate_sbml_model` function or via the online validator at http://sbml.org/validator .
	`(model, errors) = validate_sbml_model(filename)`
If the model is valid and cannot be read please open an issue at https://github.com/opencobra/cobrapy/issues .

**Comment by mdifilippo** [comment]
Hi! Is your gurobi license up to date?
